# Generated by Django 4.2.2 on 2023-07-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_employee_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="supervisor",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
